<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegionTable extends Doctrine_Table
{
	public function getRecordAsArray($country)
	{
		$array = array();
		$regions = $this->createQuery('r')->where('r.pays = ? ', $country)->execute();
		foreach($regions as $region)
		{
			$array[$region->getId()] = $region->getNom(); 
		}
		
		return $array;
	}
}