<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAnnonce extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('annonce');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('etat_de_validation', 'string', 8, array(
             'type' => 'string',
             'default' => 'wait',
             'length' => '8',
             ));
        $this->hasColumn('ville', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '30',
             ));
        $this->hasColumn('code_postal', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('contenu', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('titre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('prix', 'decimal', 65, array(
             'type' => 'decimal',
             'scale' => false,
             'length' => '65',
             ));
        $this->hasColumn('est_abusif', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'length' => '4',
             ));
        $this->hasColumn('type_annonce', 'string', 7, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '7',
             ));
        $this->hasColumn('categorie', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('region', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('departement', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '4',
             ));
        $this->hasColumn('telephone', 'string', 10, array(
             'type' => 'string',
             'length' => '10',
             ));
        $this->hasColumn('annonceur', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('validee_par', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('date_control', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Annonceur', array(
             'local' => 'annonceur',
             'foreign' => 'id'));

        $this->hasOne('Administrateur', array(
             'local' => 'validee_par',
             'foreign' => 'id'));

        $this->hasOne('Region', array(
             'local' => 'region',
             'foreign' => 'id'));

        $this->hasOne('Departement', array(
             'local' => 'departement',
             'foreign' => 'code_dep'));

        $this->hasOne('Categorie', array(
             'local' => 'categorie',
             'foreign' => 'id'));

        $this->hasMany('AnnoncePhoto', array(
             'local' => 'id',
             'foreign' => 'annonce_id'));
    }
}