<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseDepartement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('departement');
        $this->hasColumn('code_dep', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => '4',
             ));
        $this->hasColumn('nom', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('region', 'integer', 4, array(
             'type' => 'integer',
             'default' => '0',
             'notnull' => true,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Region', array(
             'local' => 'region',
             'foreign' => 'id'));

        $this->hasMany('Annonce', array(
             'local' => 'code_dep',
             'foreign' => 'departement'));
    }
}