<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseCodePostaux extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('code_postaux');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('commune', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('codepos', 'string', 5, array(
             'type' => 'string',
             'fixed' => 1,
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('departement', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '50',
             ));
        $this->hasColumn('insee', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '10',
             ));
    }

}