<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Annonce extends BaseAnnonce
{
	public function getDateMiseEnLigne() {
		$iTime=strtotime( $this->getDate_control() );
		return format_date( $iTime, 'd MMM');
	}

	public function getHeureMiseEnLigne() {
		$iTime=strtotime( $this->getDate_control() );
		return format_date( $iTime, 'H:mm');
	}
	
	public function getFilename() {
		return "un_nom";
	}
}