<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Annonceur extends BaseAnnonceur
{
	public function getPseudo() {
		$aAnnonceur=explode('@',$this->getSfGuardUser()->getUsername());
		return $aAnnonceur[0];
	}
		
	public function __toString(){
		return $this->getSfGuardUser()->getUsername();
	}
}