<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/01/25 15:48:16
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
