<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseAnnoncePhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('annonce_photo');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '8',
             ));
        $this->hasColumn('annonce_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => '4',
             ));
        $this->hasColumn('filename', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    $this->hasOne('Annonce', array(
             'local' => 'annonce_id',
             'foreign' => 'id'));
    }
}