<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUser extends PluginsfGuardUser
{
  public function setUp()
  {
    parent::setUp();
    $this->hasOne('Annonceur as Profile', array(
             'local' => 'id',
             'foreign' => 'sf_guard_user_id'));
    }
}